{ config, pkgs, lib, modulesPath, ... }:

{
  ##############################################################################
  # Base imports — minimal system + your autogenerated hardware config
  ##############################################################################
  imports = [
    ./hardware-configuration.nix
  ];

  ##############################################################################
  # Hostname
  ##############################################################################
  networking.hostName = "rpi5";

  # Use NetworkManager for WiFi/Ethernet
  networking.networkmanager.enable = true;

  ##############################################################################
  # SSH Access
  ##############################################################################
  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "prohibit-password";
      PasswordAuthentication = false;
    };
  };

  # Root SSH key
  users.users.root.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBtghfDdBX+s+XnZbnP3kiV83dCVymSO4Zhv/SudP8pS"
  ];

  hardware.raspberry-pi.extra-config = ''
    [all]
    initramfs initrd followkernel
    dtparam=nvme
    dtparam=pciex1_gen=3
    pcie_probe=1
  '';
  ##############################################################################
  # User Account
  ##############################################################################
  users.users.ian = {
    isNormalUser = true;
    extraGroups = [ "wheel" ];
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBtghfDdBX+s+XnZbnP3kiV83dCVymSO4Zhv/SudP8pS"
    ];
  };

  ##############################################################################
  # System Basics
  ##############################################################################
  time.timeZone = "America/Los_Angeles";

  # Good for Pi systems — reduce SD/NVMe wear
  zramSwap.enable = true;

  # Core packages
  environment.systemPackages = with pkgs; [
    vim git wget curl htop wezterm
  ];

  # flakes
  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];

  ##############################################################################
  # State version (do not change after installation)
  ##############################################################################
  system.stateVersion = "24.05";
}
